apiVersion: v1
kind: Namespace
metadata:
  name: antrea-capture
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capture-controller
  namespace: antrea-capture
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capture-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capture-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capture-controller
subjects:
  - kind: ServiceAccount
    name: capture-controller
    namespace: antrea-capture
